In [4]:
import numpy as np
import PIL
from PIL import Image, ImageFilter
import torch

c:\Users\anayp\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [5]:
directory = "indoor/Images/"
image = Image.open(directory + "airport_inside/airport_inside_0001.jpg").convert("L")

np_image = np.asarray(image)

sobel_filter_vertical = np.array([
    [1, 0, -1],
    [2, 0, -2],
    [1, 0, -1]
])

sobel_filter_horizontal = np.array([
    [1, 2, 1],
    [0, 0, 0],
    [-1, -2, -1]
])

scharr_filter_vertical = np.array([
    [],
    [],
    []
])

scharr_filter_horizontal = np.array([
    [],
    [],
    []
])


In [6]:
def convolve(image, kernel, padding=0):
    # Get input and kernel dimensions
    h, w = image.shape
    kh, kw = kernel.shape
    
    # Calculate the output shape
    oh, ow = h - kh + 1, w - kw + 1
    
    # Apply padding if specified
    if padding > 0:
        image = np.pad(image, padding, mode='constant')
        oh, ow = h + 2*padding - kh + 1, w + 2*padding - kw + 1
    
    # Create an empty output array
    output = np.zeros((oh, ow))
    
    # Slide the kernel over the input image and compute the dot product at each position
    for i in range(oh):
        for j in range(ow):
            output[i, j] = np.sum(image[i:i+kh, j:j+kw] * kernel)
            
    return output

In [9]:
#Testing convolutions

test_np_image = []
for i in range(6):
    test_np_image.append([])
    for j in range(6):
        if j >= 3: test_np_image[i].append(10)
        else: test_np_image[i].append(0)
test_np_image = np.array(np_image)

sobel_filter_vertical = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

filtered_image = np.array(convolve(test_np_image, sobel_filter_vertical))
print(filtered_image)

[[  13.   29.   36. ... -133.  -95.  -67.]
 [  35.   35.   11. ... -151. -106.  -71.]
 [  11.   24.   21. ... -130. -118.  -79.]
 ...
 [  22.   18.  -17. ...  150.   33.   -6.]
 [   1.   -8.   -6. ...  148.   42.    3.]
 [ -12.  -43.  -27. ...  143.   37.    7.]]
